version: "3"

services:
    book_api_mysql:
        build:
            context: .
            dockerfile: local/Dockerfile.mysql
        image: book_api_mysql
        command: mysqld --character-set-server=utf8mb4 --character-set-filesystem=utf8mb4
        ports:
          - "13306:3306"
        volumes:
          - book_api_mysql:/var/lib/mysql
        environment:
          MYSQL_DATABASE: book_api
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: system  
          MYSQL_PASSWORD: system 
        networks:
          - book_api 

volumes:
    book_api_mysql:
networks:
    book_api:
